# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd042853564217f51eef98f53bf29aaf63ba9a5cc55b301d37c27da868c194239e8ea00ae69599b4a45f8ca02ff98db35fdae5bb57c4ae1410827b834d1df6df

test:
  secret_key_base: e48ee09cc7cc1cd36d3530e6eeecf2ebe02dbd5677f8b64ae4171eae3fc2b889b70cb3806ee9c16b5ec6e0bbe90425779af8c8a8ce2ef46bdaa05b67789a5e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
